### ISSUE TITLE
Gene symbol collisions

### ISSUE THREAD

**Issue by tgerke** [GerkeLab/epiTAD#10]
We should figure out a way to have the gene symbol texts dodge each other. Check the APOE SNPs for a good example of when it gets messy:
rs429358, rs7412

**Comment by jhcreed** [comment]
There is already a minor amount of dodging going on but not enough for areas with a lot of genes in a small amount of space. For those it is going to look messy no matter what. So our options could be either try adding a lot more dodging and lines to show what name goes with what gene (which can get very crowded) or make it so when a user scrolls over the gene the name appears (less crowded image but less informative just glancing). Any thoughts/opinions or other ideas?

**Comment by tgerke** [comment]
One solution might be to do a quick check: if number of genes in display exceeds XX then do the mouseover idea, else display the symbols
