### ISSUE TITLE
TAD mapping 

### ISSUE THREAD

**Issue by jhcreed** [GerkeLab/epiTAD#12]
In the update-ui branch (not current master branch or website) the TAD locations are getting all messed up which are messing up everything downstream. 

original version: 
<img width="497" alt="screen shot 2018-12-28 at 11 53 53 am" src="https://user-images.githubusercontent.com/25089173/50522102-33635c80-0a97-11e9-9f6a-62d77337965d.png">

branch version:
<img width="534" alt="screen shot 2018-12-28 at 11 55 05 am" src="https://user-images.githubusercontent.com/25089173/50522122-4aa24a00-0a97-11e9-9007-f04a45860385.png">

**Comment by gadenbuie** [comment]
Okay, so to confirm, the SNP `rs12` should be in a TAD with range `8353475` to `11393475`, but in the as of 8f7d3421e7f6 the range is incorrectly displayed as `112132764` to `113372764`?

**Comment by jhcreed** [comment]
Correct but not just for that snp, it is happening multiple times including in some of the examples

**Comment by gadenbuie** [comment]
Okay, I fixed the error. Here's a minimal reprex in case this comes up again.

```r
library(haploR)
library(data.table)

packageVersion("haploR")

tad <- fread("data/IMR90_domains_hg19.bed")
colnames(tad) <- c("chr", "start_position", "end_position")
tad$chr <- gsub("chr", "", tad$chr)
tad$chr <- as.numeric(tad$chr)
tad <- tad[!is.na(tad$chr), ]

snps <- c("rs12")
dat <- queryHaploreg(snps, ldThresh = 0.8, ldPop = "EUR")
dat$chr <- as.numeric(as.character(dat$chr))
dat$pos_hg38 <- as.numeric(as.character(dat$pos_hg38))
dat<-dat[dat$rsID %in% snps,]
snp_pos<-dat$pos_hg38

tad<-tad[tad$chr==max(dat$chr,na.rm=TRUE),]
in_tad <- tad[tad$start_position<= snp_pos & tad$end_position>=snp_pos,]

in_tad
in_tad$start_position
in_tad$end_position
paste0("In a TAD! The TAD ranges from ",in_tad$start_position," to ",in_tad$end_position)
```

<details><summary>Expected results</summary>

```
> library(haploR)
> library(data.table)
data.table 1.11.6  Latest news: r-datatable.com
>
> packageVersion("haploR")
[1] ‘2.0.6’
>
> tad <- fread("data/IMR90_domains_hg19.bed")
> colnames(tad) <- c("chr", "start_position", "end_position")
> tad$chr <- gsub("chr", "", tad$chr)
> tad$chr <- as.numeric(tad$chr)
Warning message:
NAs introduced by coercion
> tad <- tad[!is.na(tad$chr), ]
>
> snps <- c("rs12")
> dat <- queryHaploreg(snps, ldThresh = 0.8, ldPop = "EUR")
> dat$chr <- as.numeric(as.character(dat$chr))
> dat$pos_hg38 <- as.numeric(as.character(dat$pos_hg38))
> dat<-dat[dat$rsID %in% snps,]
> snp_pos<-dat$pos_hg38
>
> tad<-tad[tad$chr==max(dat$chr,na.rm=TRUE),]
> in_tad <- tad[tad$start_position<= snp_pos & tad$end_position>=snp_pos,]
>
> in_tad
   chr start_position end_position
1:   7        8353475     11393475
> in_tad$start_position
[1] 8353475
> in_tad$end_position
[1] 11393475
d_position)n a TAD! The TAD ranges from ",in_tad$start_position," to ",in_tad$end
[1] "In a TAD! The TAD ranges from 8353475 to 11393475"
```
</details>

**Comment by jhcreed** [comment]
Just so I know for my own reference, what was the issue? the code above exactly matches the original but not the dev version (because of all the extra code). Was it needing to add the ` x <- x$result` bit?

**Comment by gadenbuie** [comment]
Yeah, `safe_queryHaploreg()` returns a list with `result` and `error`, where `error` is `NULL` when the function works and otherwise returns the error message without breaking the app.

So I had missed pulling out `x$result` before trying to modify the columns in `x$result`. Plus I refactored a little bit so that that code chunk only does the processing _after_ verifying that the query worked.
