### ISSUE TITLE
epiTAD version

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/epiTAD#2]
In order to keep things in sync between the GitHub repo and the docker container, it'll be a good idea to start adding a version number to epiTAD. The simplest way will be to just use git tags for tracking the version number, which we can do from the Releases tab on GitHub or from the command line with git.

Either way, what version number should we start at? 

And are there expected upcoming changes to the app or repo before we'd be ready to tag a release?

**Comment by gadenbuie** [comment]
ping @tgerke @jhcreed

**Comment by gadenbuie** [comment]
I like `1.0.0`. I'm probably going to need to add a couple more commits for some docker things -- do you have any other changes planned?

**Comment by tgerke** [comment]
i was going to propose 867.5.309 but i suppose 1.0.0 will work too.

**Comment by gadenbuie** [comment]
Coming back to this to propose that we tag the NAR submission at `1.0.0`.

In general, I like semantic versioning but it can be hard to figure out how to handle version updating for projects like these. The [Semantic Versioning page](https://semver.org/) is a good intro, but the guidance is vague relative to a Shiny app or data science product. This article on [semver for data science](https://www.bryanwhiting.com/2018/07/semantic-versioning-for-data-science-models/) provides an interesting perspective.

In that line, I propose we bump from version `l.m.n` according to these guidelines:

- **major** `l+1.0.0`
  - release associated with publication submission
  - substantial rewrite of app
  - changing underlying data sources (e.g. replacing existing data with data from a new source, not just an update of data)
- **minor** `l.m+1.0`
  - breaking changes in user-facing portion of the app (e.g. removing a figure from app)
  - adding a new user-facing feature (e.g. adding a new table)
  - updating data sources to latest version
- **patch** `l.m.n+1`
  - backend changes that don't break app behavior (e.g. refactoring logic)
  - changes that improve existing features (e.g. adding color options to a plot feature)

- **dev** `l.m.n.9000`
  - indicates that a feature is not complete yet

Not every commit needs a version: the version number only needs to be changed when the app is updated on the server. I wrote a script ([build.sh](https://github.com/GerkeLab/epiTAD/blob/master/build.sh)) to automate setting and propagating the version number.

**Comment by gadenbuie** [comment]
Okay, I tagged the NAR submission version to `0.1.0` in 264abf8. We can save `1.0.0` for the manuscript.
