### ISSUE TITLE
Allow user to select from set of pre-loaded examples

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/epiTAD#4]
@tgerke:
> the hover for the examples could potenially then not just include rsIDs but a reason for why they're interesting (risk loci for prostate cancer: rs123, rs1234, ...)

> what if you fed epiTAD a list of all known cancer risk snps in 8q24?

@tgerke @jhcreed I can implement the UI if you send me the epiTAD bookmark link and associated text for the examples you'd like to include.

**Comment by jhcreed** [comment]
Example 1  (many snps - potentially txt file example): 

Chromosome 8q24 cancer risk loci: https://apps.gerkelab.com/epiTAD/?_inputs_&oncoParameters1=null&oncoParameters2=null&oncoParameters3=null&oncoParameters4=null&parameters=%5B%22pos_hg38%22%2C%22r2%22%2C%22query_snp_rsid%22%5D&parameters2=%5B%22%23chromosome%22%2C%22coordinate%22%2C%22hits%22%2C%22score_anno%22%5D&plotColor=%221%22&plotEndBP=127810818&plotStartBP=126730818&pop=%22EUR%22&resetBP=0&sidebarCollapsed=false&sidebarItemExpanded=null&snpList=%22rs1016343%2Crs10505477%2Crs9642880%2Crs13281615%2Crs1447295%2Crs1562430%2Crs16901979%2Crs16902094%2Crs2456449%2Crs4242382%2Crs4242384%2Crs445114%2Crs6983267%2Crs7014346%22&tabs=%22tab1%22&update1=7&updateBP=0&value=0.8

**Comment by jhcreed** [comment]
Example 2 (two snps): 

Ancestry informative markers: rs1229984, rs3811801
https://apps.gerkelab.com/epiTAD/?_inputs_&oncoParameters1=null&oncoParameters2=null&oncoParameters3=null&oncoParameters4=null&parameters=%5B%22pos_hg38%22%2C%22r2%22%2C%22query_snp_rsid%22%5D&parameters2=%5B%22%23chromosome%22%2C%22coordinate%22%2C%22hits%22%2C%22score_anno%22%5D&plotColor=%221%22&plotEndBP=100020977&plotStartBP=99020977&pop=%22EUR%22&resetBP=0&sidebarCollapsed=false&sidebarItemExpanded=null&snpList=%22rs1229984%2C%20rs3811801%22&tabs=%22tab1%22&update1=8&updateBP=0&value=0.8

**Comment by gadenbuie** [comment]
@jhcreed @tgerke How do you want to format the button/link text? Here's what it looks like using the text from above:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/5420529/50491326-b7f2a400-09df-11e9-8482-f59ade5f5e88.png">

If you want to write a short sentence describing what's interesting about each of the examples, I may be able to throw together a tooltip that appears next to the example when you mouse over the menu item, kind of like this:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/5420529/50491371-f9834f00-09df-11e9-887d-59746d2aafdf.png">

**Comment by jhcreed** [comment]
They could be "AIMs", "DNA damage" and "8q24 Cancer Risk" ?

**Comment by gadenbuie** [comment]
@jhcreed We have plenty of space, especially with the tooltips. I think we should try to make the names maximally informative to a broad audience.

Another thought would be to add a non-link header in the drop-up menu that starts a sentence that the list entries finish. Maybe something like 

_A selection of SNPS that are..._

- Potentially protective of DNA damage
- Informative ancestry markers
- Cancer risk loci for Chromosome 8q24

**Comment by jhcreed** [comment]
Ancestry informative markers other than informative ancestry markers but other than that sure! I thought you were trying to make them even shorter

**Comment by jhcreed** [comment]
examples do not match with names
