### ISSUE TITLE
Relocate "Info" for better use of screen space

### ISSUE THREAD

**Issue by tgerke** [GerkeLab/epiTAD#8]
We have a retractable layout that, by default, uses a lot of screen space. But this layout only covers two views: the main query page and the info page. Might it be better to place the info page as a tab/link, flush right in the top bar?

**Comment by gadenbuie** [comment]
Unfortunately the Shiny Dashboard layout doesn't provide a way to change the selected tab (or main content area) via buttons in the top navbar. But there's not a lot of text in the Info tab, so I think we could get away with adding a link to the navbar that triggers a modal. I'll work up a quick example.

**Comment by gadenbuie** [comment]
Okay, so Shiny Dashboard really locks you into the sidebar layout, even though the underlying framework (AdminLTE) could easily handle the navbar layout.

It is nice to have the extra space for the app without the sidebar.

Here's one option for moving the info UI. In this case, I added it into the examples drop-up button. Thoughts?

![epitad-about-dialog](https://user-images.githubusercontent.com/5420529/50519295-330f9500-0a88-11e9-92e6-a803028de99b.gif)

**Comment by gadenbuie** [comment]
We could also try to add dropdown menus to the nav bar for the Examples and the info ... but this would require some hacking. shinyDashboard gives you [three menu type options](https://rstudio.github.io/shinydashboard/structure.html#message-menus) that basically _have_ to look like this.

![](https://rstudio.github.io/shinydashboard/images/header.png)

**Comment by jhcreed** [comment]
I like the idea of a pop-up info page but Im not sure if people looking for additional info would know to look under example queries

**Comment by gadenbuie** [comment]
I agree, this is definitely a limitation. I also tried adding it as a separate button to the right of "Example queries" with just an info icon, but it felt a little crowded. On second thought, though I think it's probably the best choice to get out of tabs for now and we can revisit later. Will update the PR shortly.

**Comment by tgerke** [comment]
I love the way this works and looks, but do agree with @jhcreed that we should brainstorm a way to get this out of the Examples link in the future. For now, the operation is pretty slick, and it helps to get all that real estate back.

**Comment by gadenbuie** [comment]
Here's the version with the separate button. I guess we could also shorten the "Example Queries" button to just "Examples".

![epitad-about-dialog2](https://user-images.githubusercontent.com/5420529/50525763-7b8c7a00-0aab-11e9-8a9e-a1632ac1bcec.gif)
